### PR TITLE
fix: updated the variable description

### PR DESCRIPTION
**Pull request by imprateeksh**
### Description
 - Issue : [#7](https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/issues/7)
 - Please refer [comment](https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/pull/4#discussion_r1542612475) for further information.

### Release required?

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by SirSpidey** [comment]
@imprateeksh: @hlucey is going to review this because she's working on other content for the DA.

**Comment by hlucey** [comment]
@imprateeksh I've added a few edits to the PR. 

In addition, to match the other variable strings, I'd like to attach the following learn more link to the project tag description: https://dataplatform.cloud.ibm.com/docs/content/wsj/getting-started/assets.html?context=wx&audience=wdp#prop-data

Let me know if you have any questions! Thanks

**Comment by imprateeksh** [comment]
Sure @hlucey, thank you for your valuable input here.
Could you please review the pull request again?

**Review by hlucey — APPROVED** [review]

**Review by SirSpidey — APPROVED** [review]
@hlucey has reviewed, so approving.

**Pull request merged**
