### PR TITLE
feat: add prefix to the watsonx project name

### PR DESCRIPTION
**Pull request by Aashiq-J**
### Description

Issue: https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/issues/23

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

add prefix to the watsonx project name

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by andreainnocenti** [comment]
@Aashiq-J please review the error

**Comment by vburckhardt** [comment]
Could we add the prefix instead of a randomly generated suffix? Randomly generated suffix are typically used for resource names that are globally unique across account (which are only cos bucket name, container registry namespace)

**Review by vburckhardt — CHANGES_REQUESTED** [review]
See comment above

**Comment by vburckhardt** [comment]
@mkrudele @andreainnocenti - ok for you?

**Review by andreainnocenti — APPROVED** [review]

**Review by vburckhardt — APPROVED** [review]

**Pull request merged**
