### PR TITLE
fix: update cos_kms_new_key_name default value

### PR DESCRIPTION
**Pull request by dishankkalra23**
### Description

This PR updates default value of cos_kms_new_key_name to append an affix  in`key_name`.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

#### Issue
https://github.ibm.com/GoldenEye/issues/issues/10963

##### Release notes content

PR updates default value of cos_kms_new_key_name to append an affix  in`key_name`.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by ocofaigh** [comment]
@dishankkalra23 I would of expected an upgrade test to fail here, but it looks like this repo doesn't have one! Can you maybe add one as part of this PR so we can at least see how it reacts to this update?

**Comment by dishankkalra23** [comment]
> @dishankkalra23 I would of expected an upgrade test to fail here, but it looks like this repo doesn't have one! Can you maybe add one as part of this PR so we can at least see how it reacts to this update?

Adding complete example in Upgrade test but it will not fail because complete example takes a value for `cos_kms_new_key_name` in the test.

**Comment by dishankkalra23** [comment]
> > @dishankkalra23 I would of expected an upgrade test to fail here, but it looks like this repo doesn't have one! Can you maybe add one as part of this PR so we can at least see how it reacts to this update?
> 
>     * Adding complete example in Upgrade test will not fail it because complete example takes a value for `cos_kms_new_key_name` in the test which will be constant: https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/blob/1ba90a867d38c0fdfeaacf76a45b7bd0783d52ea/examples/complete/main.tf#L27
> 
>     * Adding basic example to test upgrade test failure

After adding complete example, still upgrade test didn't fail.

**Comment by ocofaigh** [comment]
@dishankkalra23 The upgrade test is not failing because in the complete example, a value is being explicitly passed for the `cos_kms_new_key_name`: https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/blob/0047494ed436eabad3b0ad4ffee0d189ad435f97/examples/complete/main.tf#L27C3-L27C23

If you removed this, then I suspect it will fail, as its going to want to change it to the new default you added.

**Comment by dishankkalra23** [comment]
> @dishankkalra23 The upgrade test is not failing because in the complete example, a value is being explicitly passed for the `cos_kms_new_key_name`: https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/blob/0047494ed436eabad3b0ad4ffee0d189ad435f97/examples/complete/main.tf#L27C3-L27C23
> 
> If you removed this, then I suspect it will fail, as its going to want to change it to the new default you added.

First, I added the basic example in upgrade test which didn't have `cos_kms_new_key_name` and it didn't failed. Now it doesn't matter to test the examples as we are going to remove the examples from this module. FYI: https://github.ibm.com/GoldenEye/issues/issues/10960

**Comment by ocofaigh** [comment]
@dishankkalra23 right but I we still need to make this change. And right now all we have is the example to test the change. So please remove `cos_kms_new_key_name` from the complete example, and lets watch how upgrade test reacts

**Pull request closed without merging**
